### ISSUE TITLE
[BUG] Mod unable to load on server side forge, crashes on startup

### ISSUE THREAD

**Issue by goof-bug** [tofodroid/mimi-mod#80]
**Describe the bug**
Mod crashes on server side startup due to attempting to load invalid class.

**To Reproduce**
Try to start the forge server, no other mods installed. Server doesn't start but crashes instead instantly.

**Crash Logs**
Logs from trying to start the forge server
https://pastebin.com/ZN4UHYGC

**Environment (please complete the following information):**
 - OS: Ubuntu Server 22.04.2 LTS
 - Mod Version: 3.0.0
 - Minecraft Version: 1.19.2
 - Forge Version: 1.19.2-43.1.27

**Comment by tofodroid** [comment]
Hi @goof-bug, could you try out the 3.0.2 version of MIMI that was uploaded to [CureseForge](https://www.curseforge.com/minecraft/mc-mods/mimi-mod/files/3998580) a few days ago? This bug looks similar to one that I fixed recently that is fixed in 3.0.2: https://github.com/tofodroid/mimi-mod/issues/73

Let me know if the issue persists on that version of MIMI!

**Comment by goof-bug** [comment]
Version 3.0.2 fixed the issue!
The [modrinth page](https://modrinth.com/mod/mimi/versions) still shows 3.0.0 as the latest version which is where I downloaded MIMI but thank you for showing the correct download link.
